---
title: "Untitled"
author: "Juan Salamanca"
date: "2024-11-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
municipios <- read_excel("Municipios_da_Amazonia_Legal_2022.xlsx")

library(sf)
library(ggplot2)
library("rjson")

Brazil <- read_sf("Documents/GitHub/Trajetorias_Brazil/Brazilian_Legal_Amazon/Brazil_ADM2.geojson")

ggplot(Brazil, aes(fill = UF, color=UF)) + geom_sf() 

#Filter GeoJSON file to only include Legal Amazon
Brazil_Amazon <- Brazil[Brazil$UF %in% c("AC", "AM", "AP", "MA", "MT", "PA", "RO", "RR", "TO"),]

ggplot(Brazil_Amazon, aes(fill = UF, color="white")) + geom_sf() 

#save Brazil_Amazon dataframe as GeoJSON
st_write(Brazil_Amazon, "Documents/GitHub/Trajetorias_Brazil/Brazilian_Legal_Amazon/Brazil_Amazon.geojson")

# read network json file
# network <- fromJSON ("Documents/GitHub/Trajetorias_Brazil/Brazilian_Legal_Amazon/3_network.json")

# subset municipalities
AC <- Brazil_Amazon[Brazil_Amazon$UF == "AC",]
st_write(AC, "AC.geojson")

AM <- Brazil_Amazon[Brazil_Amazon$UF == "AM",]
st_write(AM, "AM.geojson")

AP <- Brazil_Amazon[Brazil_Amazon$UF == "AP",]
st_write(AP, "AP.geojson")

MA <- Brazil_Amazon[Brazil_Amazon$UF == "MA",]
st_write(MA, "MA.geojson")

MT <- Brazil_Amazon[Brazil_Amazon$UF == "MT",]
st_write(MT, "MT.geojson")

PA <- Brazil_Amazon[Brazil_Amazon$UF == "PA",]
st_write(PA, "PA.geojson")

RO <- Brazil_Amazon[Brazil_Amazon$UF == "RO",]
st_write(RO, "RO.geojson")

RR <- Brazil_Amazon[Brazil_Amazon$UF == "RR",]
st_write(RR, "RR.geojson")

TO <- Brazil_Amazon[Brazil_Amazon$UF == "TO",]
st_write(TO, "TO.geojson")



```
